//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsOwners.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.SwitchTable = new HashSet<SwitchTable>();
        }
    
        public int Id { get; set; }

        [Required]
        [Display(Name ="Autó márka")]
        public string CarBrand { get; set; }

        [Required]
        [Display(Name = "Autó Típus")]
        public string CarType { get; set; }

        [Required]
        [Display(Name = "Rendszám")]
        [RegularExpression(@"[A-Z]{3}-[0-9]{3}", 
            ErrorMessage = "Helyteln formátum. A formátum stílusa a következõ szerint: \"AAA-123\" (3 nagy betû, kötõjel, 3 db szám)")]
        public string LicensePlateNumber { get; set; }

        [Required]
        [Display(Name = "Gyártás Dátuma")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> DateOfProduction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwitchTable> SwitchTable { get; set; }
    }
}
